user_name: nissyi
task_types:
  - short: r
    long: Ruby
  - short: t
    long: TypeScript
  - short: o
    long: Other
  - NotHasShortHand
destinations:
  - name: Slack
    url: notification_url
    notice_types:
      - start
      - end
